/* A parser generated by meuos-buildtools bison */
/* Source: test/inputs/calc.y */


/* Simple calculator parser */
#include <stdio.h>
int yylex(void) {
    int c = getchar();
    if (c >= '0' && c <= '9') { ungetc(c, stdin); scanf("%d", &yylval); return NUMBER; }
    if (c == '+') return PLUS;
    if (c == '*') return STAR;
    if (c == '\n') return 0;
    return c;
}
void yyerror(const char *s) { fprintf(stderr, "%s\n", s); }


#ifndef YYSTYPE
#define YYSTYPE int
#endif

/* Token identifiers */
#define YYTOK_NUMBER 1
#define YYTOK_PLUS 2
#define YYTOK_STAR 3
#define YYTOK_$end 0

static const char *const yytname[] = {
  "NUMBER",
  "PLUS",
  "STAR",
  "$end",
};

static const short yyr1[] = {
  4,4,4,5,
};

static const short yyr2[] = {
  3,3,1,1,
};

static const short yydefact[] = {
  -1,  -1,  2,
};

static const short yytable[] = {
  /* 0 */ 2, 0, 0, 0,
  /* 1 */ -1, -1, -1, -1,
  /* 2 */ -1, -1, -1, -1,
};

static const short yycheck[] = {
  /* 0 */ 1, 2, 3, 0,
  /* 1 */ -1, -1, -1, -1,
  /* 2 */ -1, -1, -1, -1,
};

int yylex(void);
void yyerror(const char *);

int yyparse(void) {
  int yystate = 0;
  YYSTYPE yylval;
  int yychar;
  enum { YYSTACKDEPTH = 100 };
  YYSTYPE yyval[YYSTACKDEPTH];
  int yystack[YYSTACKDEPTH];
  int yypos = 0;
  yystack[0] = 0;
  yychar = yylex();
  for (;;) {
    int action = -1;
    if (yychar >= 0 && yychar < 4) {
      int idx = yystate * 4 + yychar;
      if (yycheck[idx] == yychar)
        action = yytable[idx];
    }
    if (action < 0) {
      action = yydefact[yystate];
      if (action < 0) {
        if (yychar == 0) return 0;
        yyerror("parse error");
        yychar = yylex();
        continue;
      }
      int n = yyr2[action];
      yypos -= n;
      yystate = yystack[yypos];
      switch (action) {
        case 0: {  $$ = $1 + $3; ; break; }
        case 1: {  $$ = $1 * $3; ; break; }
        case 2: {  $$ = $1; ; break; }
        case 3: break;
      }
      yystate = yydefact[0]; /* TODO: goto */
      yystack[++yypos] = yystate;
      yyval[yypos] = yylval;
    } else {
      yypos++;
      yystack[yypos] = action;
      yyval[yypos] = yylval;
      yychar = yylex();
    }
  }
}
