TOKEN(TNONE,          )

TOKEN(TEOF,           )
TOKEN(TNEWLINE,       )
TOKEN(TOTHER,         )

TOKEN(TNUMBER,        )
TOKEN(TCHARCONST,     )
TOKEN(TSTRINGLIT,     )

/* punctuators */
TOKEN(TLBRACK,        "[")
TOKEN(TRBRACK,        "]")
TOKEN(TLPAREN,        "(")
TOKEN(TRPAREN,        ")")
TOKEN(TLBRACE,        "{")
TOKEN(TRBRACE,        "}")
TOKEN(TPERIOD,        ".")
TOKEN(TARROW,         "->")
TOKEN(TINC,           "++")
TOKEN(TDEC,           "--")
TOKEN(TBAND,          "&")
TOKEN(TMUL,           "*")
TOKEN(TADD,           "+")
TOKEN(TSUB,           "-")
TOKEN(TBNOT,          "~")
TOKEN(TLNOT,          "!")
TOKEN(TDIV,           "/")
TOKEN(TMOD,           "%")
TOKEN(TSHL,           "<<")
TOKEN(TSHR,           ">>")
TOKEN(TLESS,          "<")
TOKEN(TGREATER,       ">")
TOKEN(TLEQ,           "<=")
TOKEN(TGEQ,           ">=")
TOKEN(TSPACESHIP,     "<=>")
TOKEN(TEQL,           "==")
TOKEN(TNEQ,           "!=")
TOKEN(TXOR,           "^")
TOKEN(TBOR,           "|")
TOKEN(TLAND,          "&&")
TOKEN(TLOR,           "||")
TOKEN(TQUESTION,      "?")
TOKEN(TCOLON,         ":")
TOKEN(TCOLONCOLON,    "::")
TOKEN(TSEMICOLON,     ";")
TOKEN(TELLIPSIS,      "...")
TOKEN(TASSIGN,        "=")
TOKEN(TMULASSIGN,     "*=")
TOKEN(TDIVASSIGN,     "/=")
TOKEN(TMODASSIGN,     "%=")
TOKEN(TADDASSIGN,     "+=")
TOKEN(TSUBASSIGN,     "-=")
TOKEN(TSHLASSIGN,     "<<=")
TOKEN(TSHRASSIGN,     ">>=")
TOKEN(TBANDASSIGN,    "&=")
TOKEN(TXORASSIGN,     "^=")
TOKEN(TBORASSIGN,     "|=")
TOKEN(TCOMMA,         ",")
TOKEN(THASH,          "#")
TOKEN(THASHHASH,      "##")

/* keyword */
TOKEN(TALIGNAS,       "alignas")
TOKEN(TALIGNOF,       "alignof")
TOKEN(TAUTO,          "auto")
TOKEN(TBOOL,          "bool")
TOKEN(TBREAK,         "break")
TOKEN(TCASE,          "case")
TOKEN(TCHAR,          "char")
TOKEN(TCONST,         "const")
TOKEN(TCONSTEXPR,     "constexpr")
TOKEN(TCONTINUE,      "continue")
TOKEN(TDEFAULT,       "default")
TOKEN(TDO,            "do")
TOKEN(TDOUBLE,        "double")
TOKEN(TELSE,          "else")
TOKEN(TENUM,          "enum")
TOKEN(TEXTERN,        "extern")
TOKEN(TFALSE,         "false")
TOKEN(TFLOAT,         "float")
TOKEN(TFOR,           "for")
TOKEN(TGOTO,          "goto")
TOKEN(TIF,            "if")
TOKEN(TINLINE,        "inline")
TOKEN(TINT,           "int")
TOKEN(TLONG,          "long")
TOKEN(TNULLPTR,       "nullptr")
TOKEN(TREGISTER,      "register")
TOKEN(TRESTRICT,      "restrict")
TOKEN(TRETURN,        "return")
TOKEN(TSHORT,         "short")
TOKEN(TSIGNED,        "signed")
TOKEN(TSIZEOF,        "sizeof")
TOKEN(TSTATIC,        "static")
TOKEN(TSTATIC_ASSERT, "static_assert")
TOKEN(TSTRUCT,        "struct")
TOKEN(TSWITCH,        "switch")
TOKEN(TTHREAD_LOCAL,  "thread_local")
TOKEN(TTRUE,          "true")
TOKEN(TTYPEDEF,       "typedef")
TOKEN(TTYPEOF,        "typeof")
TOKEN(TTYPEOF_UNQUAL, "typeof_unqual")
TOKEN(TUNION,         "union")
TOKEN(TUNSIGNED,      "unsigned")
TOKEN(TVOID,          "void")
TOKEN(TVOLATILE,      "volatile")
TOKEN(TWHILE,         "while")
TOKEN(T_ATOMIC,       "_Atomic")
TOKEN(T_BITINT,       "_BitInt")
TOKEN(T_COMPLEX,      "_Complex")
TOKEN(T_DECIMAL128,   "_Decimal128")
TOKEN(T_DECIMAL32,    "_Decimal32")
TOKEN(T_DECIMAL64,    "_Decimal64")
TOKEN(T_GENERIC,      "_Generic")
TOKEN(T_IMAGINARY,    "_Imaginary")
TOKEN(T_NORETURN,     "_Noreturn")
TOKEN(T__ALIGNOF__,   "__alignof__")
TOKEN(T__ASM__,       "__asm__")
TOKEN(T__ATTRIBUTE__, "__attribute__")
TOKEN(T__EXTENSION__, "__extension__")
TOKEN(T__REAL__,       "__real__")
TOKEN(T__IMAG__,       "__imag__")
TOKEN(T__PRAGMA__,     "_Pragma")

/* other identifiers */
TOKEN(TDEFINE,        "define")
TOKEN(TEMBED,         "embed")
TOKEN(TELIF,          "elif")
TOKEN(TELIFDEF,       "elifdef")
TOKEN(TELIFNDEF,      "elifndef")
TOKEN(TENDIF,         "endif")
TOKEN(TERROR,         "error")
TOKEN(TIFDEF,         "ifdef")
TOKEN(TIFNDEF,        "ifndef")
TOKEN(TINCLUDE,       "include")
TOKEN(TLINE,          "line")
TOKEN(TPRAGMA,        "pragma")
TOKEN(TUNDEF,         "undef")
TOKEN(TWARNING,       "warning")
TOKEN(T__VA_ARGS__,   "__VA_ARGS__")

/* keyword aliases */
TOKEN(ALIAS_ALIGNAS,       "_Alignas")
TOKEN(ALIAS_ALIGNOF,       "_Alignof")
TOKEN(ALIAS_BOOL,          "_Bool")
TOKEN(ALIAS_STATIC_ASSERT, "_Static_assert")
TOKEN(ALIAS_THREAD_LOCAL,  "_Thread_local")

/* compatibility keyword aliases */
TOKEN(ALIAS__INLINE,       "__inline")      /* XXX: what needs this? */
TOKEN(ALIAS__INLINE__,     "__inline__")    /* XXX: what needs this? */
TOKEN(ALIAS__SIGNED,       "__signed")      /* XXX: what needs this? */
TOKEN(ALIAS__SIGNED__,     "__signed__")    /* XXX: what needs this? */
TOKEN(ALIAS__THREAD,       "__thread")
TOKEN(ALIAS__TYPEOF,       "__typeof")
TOKEN(ALIAS__TYPEOF__,     "__typeof__")
TOKEN(ALIAS__VOLATILE__,   "__volatile__")  /* XXX: what needs this? */
TOKEN(ALIAS__ASM,          "__asm")
TOKEN(ALIAS__REAL,         "__real")
TOKEN(ALIAS__IMAG,         "__imag")
TOKEN(ALIAS__PRAGMA__,     "_Pragma")
