/* fp_fmt.c regression: %f/%e/%g formatting compared against host glibc.
 *
 * All inputs are C99 hex-float literals (exact IEEE-754 bit patterns), so
 * every value below is byte-identical under both meuos-libc and glibc.
 * Expected strings were generated by running this test against glibc.
 *
 * Known intentional divergence (NOT asserted here):
 *  - 0.5 %.0f -> "1": fp_fmt rounds half-up; glibc rounds half-to-even.
 *  - 1e100/2.5e300 %f integer part and 1e-100 %.17g: dto_digits falls back
 *    to the scale10 path for |value| outside the 128-bit exact range and
 *    cannot fully expand the exact decimal value there.
 */
#include <stdio.h>
#include <string.h>

static int fails;

static void
check(const char *fmt, double v, const char *want)
{
	char buf[256];
	snprintf(buf, sizeof buf, fmt, v);
	if (strcmp(buf, want) != 0) {
		printf("FAIL: %-10s => [%s], want [%s]\n", fmt, buf, want);
		fails++;
	}
}

int
main(void)
{
	double v;

	/* 3.14 */
	v = 0x1.91eb851eb851fp+1;
	check("%f", v, "3.140000");
	check("%.2f", v, "3.14");
	check("%e", v, "3.140000e+00");
	check("%.2e", v, "3.14e+00");
	check("%g", v, "3.14");
	check("%010.3f", v, "000003.140");
	check("%10.2f", v, "      3.14");
	check("%-10.2f", v, "3.14      ");
	check("%+f", v, "+3.140000");

	/* pi -- these exercises the rounding trigger (digit at precision+1) */
	v = 0x1.921fb54442d18p+1;
	check("%.6f", v, "3.141593");
	check("%.10f", v, "3.1415926536");
	check("%.4e", v, "3.1416e+00");
	check("%.6g", v, "3.14159");
	check("%.10g", v, "3.141592654");
	check("%.17g", v, "3.1415926535897931");
	/* %a/%A hex floats */
	check("%a", v, "0x1.921fb54442d18p+1");
	check("%A", v, "0X1.921FB54442D18P+1");
	check("%.3a", v, "0x1.922p+1");
	check("%a", 0x1.91eb851eb851fp+1, "0x1.91eb851eb851fp+1");	/* 3.14 */
	check("%#a", 0x1.91eb851eb851fp+1, "0x1.91eb851eb851fp+1");
	check("%a", 0x0p+0, "0x0p+0");
	check("%a", -0x1.8p+0, "-0x1.8p+0");		/* -1.5, trailing zeros stripped */
	check("%a", 0x1.b7cdfd9d7bdbbp-34, "0x1.b7cdfd9d7bdbbp-34");	/* 1e-10 */
	check("%+a", 0x1p+1, "+0x1p+1");

	/* 123456.789 -- rounding at %.0f and %.2f */
	v = 0x1.e240c9fbe76c9p+16;
	check("%.0f", v, "123457");
	check("%.2f", v, "123456.79");
	check("%.2e", v, "1.23e+05");
	check("%g", v, "123457");

	/* 999999.999 -- carry chain into a new integer digit */
	v = 0x1.e847fff7ced91p+19;
	check("%.0f", v, "1000000");
	check("%.6f", v, "999999.999000");
	check("%e", v, "1.000000e+06");

	/* small values and fractions */
	v = 0x1.999999999999ap-4;	/* 0.1 */
	check("%.17g", v, "0.10000000000000001");
	check("%g", v, "0.1");
	v = 0x1.5555555555555p-2;	/* 1/3 */
	check("%.6f", v, "0.333333");
	check("%.6e", v, "3.333333e-01");
	v = 0x1.2a05f20000000p+33;	/* 1e10 */
	check("%g", v, "1e+10");
	check("%.0f", v, "10000000000");
	check("%e", v, "1.000000e+10");

	/* negative values, sign flags */
	v = -0x1.91eb851eb851fp+1;
	check("%.2f", v, "-3.14");
	check("%+f", v, "-3.140000");
	check("%.2e", v, "-3.14e+00");

	/* 0.0 and -0.0 */
	check("%f", 0x0p+0, "0.000000");
	check("%.0f", 0x0p+0, "0");
	check("%g", 0x0p+0, "0");
	check("%f", -0x0p+0, "-0.000000");
	check("%g", -0x0p+0, "-0");

	/* 0.5 %.0f: fp_fmt rounds half-up -> "1", glibc half-to-even -> "0".
	 * Not asserted (deliberate meuos-libc semantics, see header note). */
	v = 0x1.0000000000000p-1;
	check("%g", v, "0.5");

	/* NaN / Inf */
	check("%f", (double)(1.0 / 0.0), "inf");
	check("%f", (double)(-1.0 / 0.0), "-inf");
	check("%g", (double)(1.0 / 0.0), "inf");

	if (fails) {
		printf("fp_fmt: %d FAILURES\n", fails);
		return 1;
	}
	puts("PASS fp_fmt");
	return 0;
}
