/* probe.c — meow inline feature detection (autoconf replacement).
 *
 * Parses the YAML "probe:" section and runs compile/link tests to
 * determine available headers, functions, and macros, then generates
 * config.h for the recipe. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "meow.h"

/* Temporary file helpers */
static char tmpdir[] = "/tmp/meow-probe.XXXXXX";

static int
probe_init(void)
{
	if (!mkdtemp(tmpdir))
		return -1;
	return 0;
}

static void
probe_fini(void)
{
	if (tmpdir[0] == '/') {
		char cmd[256];
		snprintf(cmd, sizeof cmd, "rm -rf %s", tmpdir);
		run(cmd);
		memcpy(tmpdir, "/tmp/meow-probe.XXXXXX", sizeof "/tmp/meow-probe.XXXXXX");
	}
}

/* Compile a minimal C snippet. Returns 0 on success, -1 on failure.
 * The snippet is written to probe.c, compiled to probe.o, then deleted. */
static int
probe_compile(const char *code, const char *cflags, const char *cc)
{
	char src[256], obj[256];
	FILE *f;
	int rc;

	snprintf(src, sizeof src, "%s/probe.c", tmpdir);
	snprintf(obj, sizeof obj, "%s/probe.o", tmpdir);

	f = fopen(src, "w");
	if (!f) return -1;
	fprintf(f, "%s\n", code);
	fclose(f);

	char cmd[2048];
	int n = snprintf(cmd, sizeof cmd, "%s %s -c -o %s %s 2>/tmp/meow-probe-err.txt",
	         cc ? cc : "mcc",
	         cflags ? cflags : "",
	         obj, src);
	if (n < 0 || (size_t)n >= sizeof(cmd)) { unlink(src); return -1; }
	rc = system(cmd);
	unlink(obj);
	unlink(src);
	unlink("/tmp/meow-probe-err.txt");
	return rc == 0 ? 0 : -1;
}

/* --- Probe data parsed from YAML --- */

#define PROBE_MAX 64

struct probe_header {
	char name[64];
};

struct probe_func {
	char name[64];
};

struct probe_macro {
	char name[64];
	char code[512];
};

static struct probe_header probe_headers[PROBE_MAX];
static size_t nprobe_headers;
static struct probe_func probe_funcs[PROBE_MAX];
static size_t nprobe_funcs;
static struct probe_macro probe_macros[PROBE_MAX];
static size_t nprobe_macros;
static char probe_cc[128] = "";
static char probe_cflags[256] = "";
static char probe_config[64] = "config.h";

void
probe_reset(void)
{
	nprobe_headers = 0;
	nprobe_funcs = 0;
	nprobe_macros = 0;
	probe_cc[0] = 0;
	probe_cflags[0] = 0;
	strcpy(probe_config, "config.h");
}

int
probe_add_header(const char *name)
{
	if (nprobe_headers >= PROBE_MAX) return -1;
	snprintf(probe_headers[nprobe_headers].name, sizeof probe_headers[0].name, "%s", name);
	++nprobe_headers;
	return 0;
}

int
probe_add_function(const char *name)
{
	if (nprobe_funcs >= PROBE_MAX) return -1;
	snprintf(probe_funcs[nprobe_funcs].name, sizeof probe_funcs[0].name, "%s", name);
	++nprobe_funcs;
	return 0;
}

int
probe_set_cc(const char *cc)
{
	snprintf(probe_cc, sizeof probe_cc, "%s", cc);
	return 0;
}

int
probe_set_cflags(const char *cflags)
{
	snprintf(probe_cflags, sizeof probe_cflags, "%s", cflags);
	return 0;
}

int
probe_set_config(const char *name)
{
	snprintf(probe_config, sizeof probe_config, "%s", name);
	return 0;
}

/* Run all registered probes and generate config.h. Returns 0 on success. */
int
probe_run(const char *build_dir)
{
	char config_path[512];
	FILE *f;
	int rc = 0;

	if (nprobe_headers == 0 && nprobe_funcs == 0)
		return 0; /* nothing to probe */
	fprintf(stderr, "meow: probe: headers=%zu funcs=%zu\n", nprobe_headers, nprobe_funcs);

	if (probe_init() != 0)
		return -1;

	snprintf(config_path, sizeof config_path, "%s/%s",
	         build_dir ? build_dir : ".",
	         probe_config);

	f = fopen(config_path, "w");
	if (!f) { probe_fini(); return -1; }

	fprintf(f, "/* config.h — generated by meow probe. */\n");
	fprintf(f, "#ifndef MEOW_CONFIG_H\n#define MEOW_CONFIG_H\n\n");

	/* Probe headers */
	for (size_t i = 0; i < nprobe_headers; ++i) {
		char code[512];
		snprintf(code, sizeof code,
		         "#include <%s>\nint main(void){return 0;}\n",
		         probe_headers[i].name);
		if (probe_compile(code, probe_cflags, probe_cc) == 0) {
			char defname[128];
			/* Convert "sys/stat.h" -> "HAVE_SYS_STAT_H" */
			const char *s = probe_headers[i].name;
			char *d = defname;
			*d++ = 'H'; *d++ = 'A'; *d++ = 'V'; *d++ = 'E'; *d++ = '_';
			while (*s) {
				if (*s == '/' || *s == '.')
					*d++ = '_';
				else
					*d++ = (*s >= 'a' && *s <= 'z') ? *s - 'a' + 'A' : *s;
				++s;
			}
			*d = 0;
			fprintf(f, "#define %s 1\n", defname);
			/* Also inject into recipe_environment */
			char envline[128];
			snprintf(envline, sizeof envline,
			         "export %s=1; ", defname);
			size_t len = strlen(recipe_environment);
			if (len + strlen(envline) < sizeof recipe_environment)
				memcpy(recipe_environment + len, envline, strlen(envline) + 1);
		}
	}

	/* Probe functions (try to link a call to the function) */
	for (size_t i = 0; i < nprobe_funcs; ++i) {
		char code[512];
		snprintf(code, sizeof code,
		         "int main(void){void *p=(void*)%s;return p?0:0;}\n",
		         probe_funcs[i].name);
		if (probe_compile(code, probe_cflags, probe_cc) == 0) {
			char defname[128];
			snprintf(defname, sizeof defname, "HAVE_%s", probe_funcs[i].name);
			/* uppercase */
			for (char *p = defname + 5; *p; ++p)
				if (*p >= 'a' && *p <= 'z') *p -= 'a' - 'A';
			fprintf(f, "#define %s 1\n", defname);
			char envline[128];
			snprintf(envline, sizeof envline, "export %s=1; ", defname);
			size_t len = strlen(recipe_environment);
			if (len + strlen(envline) < sizeof recipe_environment)
				memcpy(recipe_environment + len, envline, strlen(envline) + 1);
		}
	}

	fprintf(f, "\n#endif /* MEOW_CONFIG_H */\n");
	fclose(f);

	probe_fini();
	return rc;
}
